Add inviet-to-event functionality
manbernotas/EventPlanning pull request #7
Opened 2018-02-03 08:25 UTC by manbernotas

2018-02-03 08:47 UTC, mantasmarcinkus requested changes
Did a great job with email notification things.
Minor review changes. 👍 
However, would love to see a `factory pattern` implemented on notifications now. If we would change underlying notification system from `email` to `in-house` notification (like facebooks notification), we want to switch easily between them.
E.g. Imagine if we have the user in our system: Let's invite him via `in-house` notification; Otherwise - use email if it is provided.

2018-02-03 08:47 UTC, mantasmarcinkus commented on EventPlanning.BL/EventManager.cs
> +            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
You will get banned so quick with gmail smtp 😂 
Gmail is evil in this case, because it does not allow to send a lot of emails.

2018-02-03 08:47 UTC, mantasmarcinkus commented on EventPlanning.BL/EventManager.cs
> +            SmtpServer.Credentials = new System.Net.NetworkCredential("eventinvitator@gmail.com", "Event_3000");
Did you just add password here? ❌ 
It is really bad. Change the password and add it to Project Properties (Environment Variables). As far as I remember it is placed where you define the port for a web service.

2018-02-03 08:47 UTC, mantasmarcinkus commented on EventPlanning.BL/EventManager.cs
> +        public bool InviteToEvent(int eventId, UserData user)
This method does not adhere to SOLID principle 'S' - single responsibility principle. It does two things: Sends email and saves invitation to database.

2018-02-03 08:47 UTC, mantasmarcinkus commented on EventPlanning.service/Controllers/EventsController.cs
> +        public int GetUserId(string user)
What does this method do? Why is it calling other service? If its purpose is to check if the UserID is valid, then I would say it is business logic - not for controller to do that. 
However, it is being called from front end, so this method should not exist, or it should be moved to User service.

2018-02-03 08:47 UTC, mantasmarcinkus commented on UserManagement.DAL/Repository.cs
> +            return context.User.SingleOrDefault(u => u.UserName == user || u.Email == user).Id;
If one of the values are `null` we will have `NullPointerException`

2018-02-03 09:00 UTC, mantasmarcinkus commented
Btw. `Add inviet-to-event` has a typo. Also, let's not use hyphens (-) when writing descriptions 👍

2018-02-06 17:21 UTC, manbernotas commented on EventPlaning.BL.Tests/InvitationManagerTests.cs
> +            public void InviteToEventFail()
More explicit test fail information. InviteToEventFailUserNotFound

2018-02-06 17:21 UTC, manbernotas commented on EventPlanning.BL/InvitationManager.cs
> +            if (sentTo != "")
Empty string should be changed to string.Empty.

2018-02-06 17:21 UTC, manbernotas commented on EventPlanning.BL/InvitationManager.cs
> +            if (user.Email == null || user.Email == "")
Use String.IsNullOrEmpty

2018-02-06 17:21 UTC, manbernotas commented on EventPlanning.BL/InvitationManager.cs
> +            catch (SmtpFailedRecipientsException)
Let's try using exception filters 
https://stackoverflow.com/questions/5563397/catch-two-exceptions-in-the-same-catch-block

2018-02-06 20:02 UTC, merged